// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
// Do not edit this file directly.
import * as React from "react";

export const Index: Record<string, any> = {
  default: {
    "input-form": {
      name: "input-form",
      description: "",
      type: "registry:ui",
      registryDependencies: ["input", "button", "form", "sonner"],
      files: [
        {
          path: "registry/ui/input-form.tsx",
          type: "registry:ui",
          target: "",
        },
      ],
      component: React.lazy(() => import("@/registry/ui/input-form")),
      source: "",
      category: "",
      subcategory: "",
      chunks: [],
    },
    "select-form": {
      name: "select-form",
      description: "",
      type: "registry:ui",
      registryDependencies: ["select", "button", "form", "sonner"],
      files: [
        {
          path: "registry/ui/select-form.tsx",
          type: "registry:ui",
          target: "",
        },
      ],
      component: React.lazy(() => import("@/registry/ui/select-form")),
      source: "",
      category: "",
      subcategory: "",
      chunks: [],
    },
    "calendar-form": {
      name: "calendar-form",
      description: "",
      type: "registry:ui",
      registryDependencies: ["calendar", "button", "form", "sonner"],
      files: [
        {
          path: "registry/ui/calendar-form.tsx",
          type: "registry:ui",
          target: "",
        },
      ],
      component: React.lazy(() => import("@/registry/ui/calendar-form")),
      source: "",
      category: "",
      subcategory: "",
      chunks: [],
    },
  },
};
