// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
// Do not edit this file directly.
import * as React from "react";

export const Index: Record<string, any> = {
  default: {
    "input-form": {
      name: "input-form",
      description: "",
      type: "registry:component",
      registryDependencies: ["input", "button", "form", "sonner"],
      files: [
        {
          path: "registry/component/input/input-form.tsx",
          type: "registry:component",
          target: "",
        },
      ],
      component: React.lazy(
        () => import("@/registry/component/input/input-form")
      ),
      source: "",
      category: "",
      subcategory: "",
      chunks: [],
    },
    "select-form": {
      name: "select-form",
      description: "",
      type: "registry:component",
      registryDependencies: ["select", "button", "form", "sonner"],
      files: [
        {
          path: "registry/component/select/select-form.tsx",
          type: "registry:component",
          target: "",
        },
      ],
      component: React.lazy(
        () => import("@/registry/component/select/select-form")
      ),
      source: "",
      category: "",
      subcategory: "",
      chunks: [],
    },
  },
};
