// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
// Do not edit this file directly.
import * as React from "react";

export const Index: Record<string, any> = {
  default: {
    "input-form": {
      name: "input-form",
      description: "",
      type: "registry:ui",
      registryDependencies: ["input", "button", "form", "sonner"],
      files: [
        {
          path: "registry/ui/input-form.tsx",
          type: "registry:ui",
          target: "",
        },
      ],
      component: React.lazy(() => import("@/registry/ui/input-form")),
      source: "",
      category: "",
      subcategory: "",
      chunks: [],
    },
    "select-form": {
      name: "select-form",
      description: "",
      type: "registry:ui",
      registryDependencies: ["select", "button", "form", "sonner"],
      files: [
        {
          path: "registry/ui/select-form.tsx",
          type: "registry:ui",
          target: "",
        },
      ],
      component: React.lazy(() => import("@/registry/ui/select-form")),
      source: "",
      category: "",
      subcategory: "",
      chunks: [],
    },
    "date-picker-form": {
      name: "date-picker-form",
      description: "",
      type: "registry:ui",
      registryDependencies: ["calendar", "button", "form", "sonner", "popover"],
      files: [
        {
          path: "registry/ui/date-picker-form.tsx",
          type: "registry:ui",
          target: "",
        },
      ],
      component: React.lazy(() => import("@/registry/ui/date-picker-form")),
      source: "",
      category: "",
      subcategory: "",
      chunks: [],
    },
    "tag-input-form": {
      name: "input-form",
      description: "",
      type: "registry:ui",
      registryDependencies: ["input", "button", "form", "sonner"],
      files: [
        {
          path: "registry/ui/tag-input-form.tsx",
          type: "registry:ui",
          target: "",
        },
      ],
      component: React.lazy(() => import("@/registry/ui/tag-input-form")),
      source: "",
      category: "",
      subcategory: "",
      chunks: [],
    },
    multiselect: {
      name: "multiselect",
      description: "",
      type: "registry:ui",
      registryDependencies: ["command"],
      files: [
        {
          path: "registry/ui/multiselect.tsx",
          type: "registry:ui",
          target: "",
        },
        {
          path: "registry/ui/multiselect.tsx",
          type: "registry:ui",
          target: "",
        },
      ],
      component: React.lazy(() => import("@/registry/ui/multiselect")),
      source: "",
      category: "",
      subcategory: "",
      chunks: [],
    },
    "multiselect-form": {
      name: "multiselect-form",
      description: "",
      type: "registry:ui",
      registryDependencies: ["command", "button", "form", "sonner"],
      files: [
        {
          path: "registry/ui/multiselect-form.tsx",
          type: "registry:ui",
          target: "",
        },
        {
          path: "registry/ui/multiselect.tsx",
          type: "registry:ui",
          target: "",
        },
      ],
      component: React.lazy(() => import("@/registry/ui/multiselect-form")),
      source: "",
      category: "",
      subcategory: "",
      chunks: [],
    },
    "phone-input-form": {
      name: "input-form",
      description: "",
      type: "registry:ui",
      dependencies: ["react-phone-number-input"],
      registryDependencies: ["button", "form", "sonner"],
      files: [
        {
          path: "registry/ui/phone-input-form.tsx",
          type: "registry:ui",
          target: "",
        },
      ],
      component: React.lazy(() => import("@/registry/ui/phone-input-form")),
      source: "",
      category: "",
      subcategory: "",
      chunks: [],
    },
    "dual-range-slider-form": {
      name: "dual-range-slider-form",
      description: "",
      type: "registry:ui",
      registryDependencies: ["button", "form", "sonner", "slider"],
      files: [
        {
          path: "registry/ui/dual-range-slider-form.tsx",
          type: "registry:ui",
          target: "",
        },
      ],
      component: React.lazy(
        () => import("@/registry/ui/dual-range-slider-form")
      ),
      source: "",
      category: "",
      subcategory: "",
      chunks: [],
    },
    "date-expression-input-form": {
      name: "date-expression-input-form",
      description: "",
      type: "registry:ui",
      dependencies: ["yeezy-dates"],
      registryDependencies: ["input", "button", "form", "sonner"],
      files: [
        {
          path: "registry/ui/date-expression-input-form.tsx",
          type: "registry:ui",
          target: "",
        },
      ],
      component: React.lazy(
        () => import("@/registry/ui/date-expression-input-form")
      ),
      source: "",
      category: "",
      subcategory: "",
      chunks: [],
    },
    "date-range-picker-form": {
      name: "date-range-picker-form",
      description: "",
      type: "registry:ui",
      registryDependencies: ["calendar", "button", "form", "sonner", "popover"],
      files: [
        {
          path: "registry/ui/date-range-picker-form.tsx",
          type: "registry:ui",
          target: "",
        },
      ],
      component: React.lazy(
        () => import("@/registry/ui/date-range-picker-form")
      ),
      source: "",
      category: "",
      subcategory: "",
      chunks: [],
    },
  },
};
